### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by jaohbib** [StabiBerlin/sbb-relevance-test#113]
I tried to run this on my Gitlab  I hadd to add some dependencies  in my ci file

    - apt-get install -y -qq xvfb libnss3-dev libgdk-pixbuf2.0-dev libgtk-3-dev libxss-dev libasound2 

is this a local problem or should i open a pull request ?

**Comment by duncdrum** [comment]
@jaohbib the gitlab config is pretty much untested, as we are mainly running on GitHub now. Any PR to improver it would be greatly welcome

**Comment by jaohbib** [comment]
done

Von: Duncan Paterson ***@***.***>
Gesendet: Freitag, 18. Oktober 2024 15:08
An: StabiBerlin/sbb-relevance-test ***@***.***>
Cc: jaohbib ***@***.***>; Mention ***@***.***>
Betreff: Re: [StabiBerlin/sbb-relevance-test] Missing dependencies (Issue #113)


@jaohbib<https://github.com/jaohbib> the gitlab config is pretty much untested, as we are mainly running on GitHub now. Any PR to improve it would be greatly welcome
