### ISSUE TITLE
Failed test "African American Review"

### ISSUE THREAD

**Issue by annekauf** [StabiBerlin/sbb-relevance-test#78]
After being nonplussed for days why cypress test fails whereas Ranking1 Frontend shows desired Ranking, namely "Journal entries before journal volumes" I am wondering about this:

For the test to be green the html field called 'media-type" must contain the given term. As far as I see, the html field is called 'mediatype_str_mv'. Even if this doesn't matter: the journal "African American Review" only contains 'c' in that field. Therefore, the test fails ALTHOUGH the hits are according to the right sequel: journal before journal volume.
Also: second hit is digital journal - which anyway would never contain `Zeitschrift (gedruckt)` which would make 'gedruckt' a problem. As it would be with any digital journal, right?

Another question referring to test lines 20+23:
https://github.com/StaatsbibliothekBerlin/sbb-relevance-test/blob/4ad25736a343eeb1ae40fdcb1fdf62115e2c7b62/cypress/e2e/nested.cy.js#L19

Does this mean any number of results containing 'Zeitschrift gedruckt' should be listet higher than any number of results containing 'Band einer Zeitschrift'?

**Comment by annekauf** [comment]
this issue has been solved by referenced commit, no?

**Comment by duncdrum** [comment]
@annekauf once the commit is merged it will be closed automatically. The PR is still open

**Comment by annekauf** [comment]
Should PR be merged? Did I miss it?

________________________________________

Annette Kaufmann
Benutzungsabteilung, E-Services und Kommunikation
Staatsbibliothek zu Berlin – Preußischer Kulturbesitz

+49 30 266 433 559
***@***.***

Im Rahmen der E-Mail-Kommunikation werden gegebenenfalls personenbezogene Daten verarbeitet. Unsere Hinweise zum Datenschutz finden Sie hier: http://sbb.berlin/datenschutz

Von: Duncan Paterson ***@***.***>
Gesendet: Mittwoch, 17. Juli 2024 18:08
An: StaatsbibliothekBerlin/sbb-relevance-test ***@***.***>
Cc: Kaufmann, Annette ***@***.***>; Mention ***@***.***>
Betreff: Re: [StaatsbibliothekBerlin/sbb-relevance-test] Failed test "African American Review" (Issue #78)


@annekauf<https://github.com/annekauf> once the commit is merged it will be closed automatically. The PR is still open

**Comment by duncdrum** [comment]
you should rebase on `main` first. If everything is green on github, we need to check ranking1 with the modifications of the yaml.
